image: gcc

before_script:
 - apt-get update --yes
 - apt-get install --yes cmake
 - apt-get install -y -qq git make clang

build:
  stage: build
  script:
    - mkdir build && cd build
    - CXX=clang++ cmake ..
    - make
  artifacts:
    paths:
      - mybinary

test:
  stage: test
  script:
    - mkdir build && cd build
    - CXX=clang++ cmake ..
    - make
    - ./tests/utility_fuzzer_test -max_total_time=60
