image: archlinux/base

services:
- docker

build:
    stage: build
    before_script:
      - pacman -Syu clang cmake make --noconfirm
    script:
        - CXX=clang++ cmake ..
        - make


test:
    stage: test
    script:
        - ./tests/utility_fuzzer_test -max_total_time=60
